# Generated by Django 5.2.4 on 2025-08-04 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('condition_stock', models.CharField(blank=True, default='', max_length=400, verbose_name='Conditions de stockage')),
                ('nb_FDS', models.PositiveIntegerField(default=0, verbose_name='Nombre de FDS')),
                ('date_reception', models.DateField(verbose_name='Date de réception')),
                ('fournisseur', models.CharField(max_length=200, verbose_name='Fournisseur')),
                ('ref', models.CharField(max_length=200, verbose_name='Référence')),
                ('nb_lot', models.CharField(max_length=200, verbose_name='Numéro de lot')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur ayant ajouté')),
            ],
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=6)),
                ('quantite', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.produit')),
            ],
        ),
    ]
