# Generated by Django 5.2.4 on 2025-08-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0002_mouvementstock_commentaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='fiche_pdf',
            field=models.FileField(blank=True, null=True, upload_to='fiches_pdf/'),
        ),
    ]
