# Generated by Django 5.2.4 on 2025-08-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0003_produit_fiche_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
