# Generated by Django 5.2.4 on 2025-08-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0004_alter_mouvementstock_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='fichier_CA',
            field=models.FileField(blank=True, null=True, upload_to='fichier_CA/'),
        ),
        migrations.AddField(
            model_name='produit',
            name='fichier_FDS',
            field=models.FileField(blank=True, null=True, upload_to='fichier_FDS/'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='fiche_pdf',
            field=models.FileField(blank=True, null=True, upload_to='fichier_FDS/'),
        ),
    ]
