# Generated by Django 5.2.4 on 2025-08-07 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0005_produit_fichier_ca_produit_fichier_fds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='fiche_pdf',
        ),
    ]
