# Generated by Django 5.2.4 on 2025-08-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0006_remove_produit_fiche_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='nb_FDS',
            field=models.PositiveIntegerField(default=0, verbose_name='Numero de FDS'),
        ),
    ]
