# Generated by Django 5.2.4 on 2025-08-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0007_alter_produit_nb_fds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='type_mouvement',
            field=models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=10),
        ),
    ]
