# Generated by Django 5.2.4 on 2025-08-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0008_alter_mouvementstock_type_mouvement'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementstock',
            name='nb_lot',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Numéro de lot'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='ref',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Référence'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='fournisseur',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fournisseur'),
        ),
    ]
