# Generated by Django 5.2.4 on 2025-08-07 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0009_mouvementstock_nb_lot_mouvementstock_ref_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('numero_fds', models.CharField(max_length=100, verbose_name='Numéro FDS')),
                ('condition_stock', models.TextField(blank=True, verbose_name='Conditions de stockage')),
                ('consigne_utilisation', models.TextField(blank=True, verbose_name="Consignes d'utilisation")),
                ('fichier_FDS', models.FileField(blank=True, null=True, upload_to='fichier_FDS/', verbose_name='Fichier FDS (PDF)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mouvementstock',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='mouvementstock',
            name='nb_lot',
        ),
        migrations.RemoveField(
            model_name='mouvementstock',
            name='ref',
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='fournisseur',
            field=models.CharField(max_length=200, verbose_name='Fournisseur'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='type_mouvement',
            field=models.CharField(choices=[('AJOUT', 'Ajout'), ('RETRAIT', 'Retrait')], max_length=10),
        ),
        migrations.CreateModel(
            name='LotProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_lot', models.CharField(max_length=100, verbose_name='Numéro de lot')),
                ('ref', models.CharField(max_length=100, verbose_name='Numéro de lot')),
                ('date_reception', models.DateField(verbose_name='Date de réception')),
                ('fournisseur', models.CharField(max_length=200, verbose_name='Fournisseur')),
                ('stock_initial', models.PositiveIntegerField(verbose_name='Quantité reçue')),
                ('fichier_CA', models.FileField(blank=True, null=True, upload_to='fichier_CA/', verbose_name='Certificat d’analyse (PDF)')),
                ('fiche_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='inventaire.ficheproduit')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='lot',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='inventaire.lotproduit'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Produit',
        ),
    ]
