# Generated by Django 5.2.4 on 2025-08-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0010_ficheproduit_remove_mouvementstock_produit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='fournisseur',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
