# Generated by Django 5.2.4 on 2025-08-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0011_alter_mouvementstock_fournisseur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotproduit',
            name='ref',
            field=models.CharField(max_length=100, verbose_name='ref'),
        ),
    ]
