# Generated by Django 5.2.4 on 2025-08-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0012_alter_lotproduit_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheproduit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
